
server:
 port: 9191
 

spring:
 config:
  import: "optional:configserver:"
 application:
  name: API-GATEWAY
 cloud:
  config:
  uri: http://${app.host-config}:8888
  gateway:
   routes:
   - id: UserService
     uri: http://${app.host-config}:8001/
     predicates:
     - Path=/api/**
   - id: ProductService
     uri: http://${app.host-config}:4000/
     predicates:
     - Path=/v1/api/waters/**
   - id: CartService
     uri: http://${app.host-config}:8000/
     predicates:
     - Path=/v2/api/**
 
  






