app:
  host-auth: localhost
  host-discovery: localhost

spring:
 application:
  name: PRODUCT-SERVICE
 config:
  import:optional:configserver:
 cloud:
  config:
   uri: http://${app.host-config}:8888
