
server:
 port: 9191
spring:
 config:
  import: "optional:configserver:"
 application:
  name: API-GATEWAY
 cloud:
  config:
   uri: http://localhost:8888
  gateway:
   routes:
   - id: ProductService
     uri: http://localhost:4000/
     predicates:
     - Path=/api/waters/**
   - id: UserService
     uri: http://localhost:8001/
     predicates:
     - Path=/api/**






